app:
  log_level: INFO
  precision: 6

database:
  type: mysql
  host: 127.0.0.1
  user: rdmuser
  password: rdmpassword
  name: rdmdb
  connect_timeout: 5

filters:
  iv:
    enabled: "IV %"  # Name pattern of instances we want to fetch data from. Use % to match anything.
    replace:
      - [ "IV ", "" ]  # Replace any "IV " with "" (nothing).
      - [ "_", " " ]  # Replace any "_" with " ".

  raid:
    enabled: "Raid %"
    replace:
      - [ "Raid ", "" ]
      - [ "_", " " ]

  quest:
    enabled: "Quest %"
    replace:
      - [ "Quest ", "" ]
      - [ "_", " " ]
